### ISSUE TITLE
LuaJ doesn't seem to support Var Args

### ISSUE THREAD

**Issue by Art-B** [luaj/luaj#13]
(I am aware I may be mistaken, but it's worth sharing)

It appears that Luaj does not support Lua var args properly.

 The following code 

   
    local function n(...) 
        local count = 0; 
        for i, s in ipairs(arg) do 
            count = count + 1; 
        end 
        return count 
    end
    
    print(n('asdf', 'qwerty'))

prints the value of "2" [in Lua on the repl](https://repl.it/@ArthurBugorski/HotThoseRelationaldatabase), but the following Java code 

   
    @org.junit.Test
    public void shouldHandleVarArgs() throws ScriptException {
        //given
        final java.io.StringWriter luaStdOut = new java.io.StringWriter();
        final org.luaj.vm2.script.LuaScriptEngine luaScriptEngine = new org.luaj.vm2.script.LuaScriptEngine();
        luaScriptEngine.getContext().setWriter( luaStdOut );
        final String scriptCode = "local function n( ... ) local count = 0; for i,s in ipairs(arg) do count = count + 1;  end return count end print( n( 'asdf', 'qwerty' ) )";
        final javax.script.CompiledScript script = luaScriptEngine.compile( scriptCode );

        //when
        script.eval();

        //then
        assertThat( luaStdOut.toString().replaceAll( System.lineSeparator(), "\n" ), is(equalTo("2\n")) );
    }

using

   
	<dependency>
		<groupId>org.luaj</groupId>
		<artifactId>luaj-jse</artifactId>
		<version>3.0.1</version>
	</dependency>

running JDK 1.8.0_144 on Windows 7 it fails with the error

   
    org.luaj.vm2.LuaError: script:1 bad argument: table expected, got nil
    
        at org.luaj.vm2.LuaValue.argerror(Unknown Source)
        at org.luaj.vm2.LuaValue.checktable(Unknown Source)
        at org.luaj.vm2.Varargs.checktable(Unknown Source)
        at org.luaj.vm2.lib.BaseLib$ipairs.invoke(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
        at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
        at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
        at org.luaj.vm2.script.LuaScriptEngine$LuajCompiledScript.eval(Unknown Source)
        at org.luaj.vm2.script.LuaScriptEngine$LuajCompiledScript.eval(Unknown Source)
        at org.luaj.vm2.script.LuaScriptEngine$LuajCompiledScript.eval(Unknown Source)
        at LuaJDemoTest.shouldHandleVarArgs(LuaJDemoTest.java:103)

but after changing `scriptCode` to the following 

   
    final String scriptCode = "local function n( ... ) local count = 0; return 2 end print( n( 'asdf', 'qwerty' ) )";

the test passes.

From [Programming in Lua](https://www.lua.org/pil/5.2.html) is the line

> The three dots (...) in the parameter list indicate that the function has a variable number of arguments. When this function is called, all its arguments are collected in a single table, which the function accesses as a hidden parameter named arg.

**Comment by fghsgh** [comment]
I don't know if this is still how varargs work in Lua 5.2. I always did something like this:
```
function f(...)
  for i,v in ipairs({...}) do
    print(i,v)
  end
end
```
...but I don't know if this works, I am just passing by and haven't run it.

**Comment by Enyby** [comment]
You must use `...` or `{...}` (if you need table).

LuaJ worked as Lua 5.2, not as Lua 5.1.
You can check your example  on https://www.lua.org/cgi-bin/demo - it issue error.

**Comment by fghsgh** [comment]
So this issue can be closed?

**Comment by Enyby** [comment]
Yep.
