### ISSUE TITLE
Creating a fork of LuaJ

### ISSUE THREAD

**Issue by plamentotev** [luaj/luaj#4]
Looks like the original LuaJ project is not longer active. As there is some interest in contributing to the project (including myself to some extend), I think the right thing to do is to create a fork of the original project. The license allows us to use the original code and extend/modify it, but in my opinion we should change the name of the project. Of course we should keep the original files copyright notices and clearly state that this is a fork of  LuaJ, but I don't think it is a good idea to keep the original name as (as far I understood) this project is not related to the original authors in any way. Also that will allow us to publish new versions to Maven.

It was suggested to use jitpack.io, but in my opinion, while technically it might work, it is not good idea. We should not publish our code pretending to be somebody else - I don't think a message is enough. A new name is much better as it clearly shows the two projects are not the same.

**Comment by plamentotev** [comment]
Well, I take my words back. I was able to contact the original authors. As they are still interested in LuaJ and it's not abandoned, I don't think there is a need of  a fork - it's better to help the original authors.

That's why I'll close the issue.

**Comment by lymenglei** [comment]
The first sight I saw this, I also think this is the official project...
But only few stars less than 100

**Comment by astronouth7303** [comment]
The original repo is still CVS, which SourceForge now only supports in read-only mode.

**Comment by headcr4sh** [comment]
I have fetched the missing two commits from the original CVS repo and added them.

To make sure that the original commit history was left untouched I had to rebase my own changes onto the original commits, though. This renders all Pull requests to this repo useless, I am afraid. -- they will need to be re-based onto the new HEAD of the master branch...
