### ISSUE TITLE
Can't use method in method

### ISSUE THREAD

**Issue by Nogitsu** [luaj/luaj#73]
Hi, I tried to use methods like
`player.setHealth( player.getHealth() )` or `logging.info( player.getHealth() )` (which are custom methods)
But when doing `player.setHealth( player.getHealth() + 1 )` I don't have any error
It works but I have a strange Exception
`org.luaj.vm2.LuaError: @init.lua:1 vm error: java.lang.NullPointerException`

[Here](https://drive.google.com/file/d/102n7o7P6dvVj3_IwGKlqS0_txz4vEMWE/view?usp=sharing) is a project with the reproduced problem

Under this are the files on pastebin:
[init.lua](https://pastebin.com/iEuZ23Uy)
[LuaJ.java](https://pastebin.com/7CnWHPsB)
[LuaLib.java](https://pastebin.com/G26ypf4e)

**Comment by jplwill** [comment]
Your `setValue` method returns `null`.  LuaJ requires that it return `LuaValue.NIL`.

Also, you might have an easier time by defining LuaLib as a plain old Java object, and using `env.set("lib", CoerceJavaToLua.coerce(new LuaLib()))` to get an object into Lua, depending on what you're wanting to do.

Your way, you get to use `.` notation; using a plain object and `coerce` you get something that uses `:` notation, like a Lua object, e.g., `lib:setValue(5)`.

**Comment by Nogitsu** [comment]
That's it ! Thanks !
