### ISSUE TITLE
Found A Recursive Bug in VarArgsFunction

### ISSUE THREAD

**Issue by NPEX42** [luaj/luaj#78]
Hello, I appear to have found a bug in the VarArgsFunction.invoke() function, when called with one LuaValue Argument the two Functions invoke and onInvoke call each other and end up blowing the call stack.

I have provided the Caller & The Callee

**Comment by NPEX42** [comment]
Added files

**Comment by wagyourtail** [comment]
isn't that because VarArgsFunction is abstract and functions that extend it should overwrite one of those two methods

**Comment by NPEX42** [comment]
The One args function is the one you are supposed to overwrite

**Comment by wagyourtail** [comment]
please read the comments in the VarArgsFunction class.

**Comment by NPEX42** [comment]
My Apologies @wagyourtail , I didnt read the documentation, But, in my own defence, All the N-ArgFunctions follow one design, and yet the VarArgFunction follows a different design, and my main source of documentation was the Luaj.org website which has no mention of var arg functions.
